apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: interview-api-hpa
  namespace: interview-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interview-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: interview-web-hpa
  namespace: interview-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interview-web
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
