apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-ingress-only
  namespace: staging
spec:
  podSelector:
    matchLabels:
      app: interview-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: interview-web
      ports:
        - protocol: TCP
          port: 4000
